name: llm-playground
channels:
  - nvidia # need to specify this as first channel to go grab the dependencies of pytorch-cuda correctly
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11.3
  - conda
  - pip
  - pytorch::pytorch>=2.2.0 # use pytorch channel
  - pytorch::pytorch-cuda=11.8 # Remove this line if your hardware does not support cuda, otherwise it will create conflicts
  - nvidia/label/cuda-11.8.0::cuda-nvcc # Remove this line if your hardware does not support cuda, otherwise it will create conflicts
  - numpy
  - pandas
  - scipy
  - pip:
    - transformers
    - tokenizers
    - accelerate
    - huggingface-hub
    - optimum
    - gradio>=4.0
    - bitsandbytes
    - sentencepiece
    - protobuf
    - tiktoken
    - textwiz
    # For flash attention 2
    - packaging
    - ninja
    - flash-attn --no-build-isolation